import { useMemo, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Code2, Box, Smartphone, Package, Container, FileCode, ChevronDown, HelpCircle } from 'lucide-react'
import { PageHeader } from '@/components/layout/PageHeader'
import { Card, CardBody } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { CleanupItemRow } from '@/components/cleanup/CleanupItemRow'
import { useAppStore } from '@/store/useAppStore'
import { formatBytes } from '@/lib/format'
import type { DeveloperTool } from '@/types'

const TOOL_META: Record<DeveloperTool, { label: string; icon: typeof Code2; whySafe: string }> = {
  xcode: {
    label: 'Xcode',
    icon: Code2,
    whySafe:
      'Xcode regenerates DerivedData, device support files, and logs automatically. Archives and old simulator runtimes are kept until you explicitly remove them — reclaiming them just means a redownload or rebuild next time you need them.',
  },
  node: {
    label: 'Node.js',
    icon: Box,
    whySafe:
      'Package manager caches (npm/yarn/pnpm) are designed to be disposable — every entry can be re-fetched from the registry. Stale node_modules folders are only flagged for projects untouched for months, and your source code is never touched.',
  },
  android: {
    label: 'Android / Gradle',
    icon: Smartphone,
    whySafe:
      'Gradle caches and build directories are regenerated automatically by the next build. Emulator images are only flagged when unused for a long stretch, and active emulators are never included.',
  },
  cocoapods: {
    label: 'CocoaPods / Ruby',
    icon: Package,
    whySafe:
      'Pod specs and gem packages are downloaded from public/private registries and can always be re-fetched with "pod install" or "gem install" — nothing project-specific is removed.',
  },
  docker: {
    label: 'Docker',
    icon: Container,
    whySafe: 'Docker integration is not connected yet in this prototype phase.',
  },
  general: {
    label: 'General Build Artifacts',
    icon: FileCode,
    whySafe:
      'Dist/build folders, temporary bundles, and old logs are regenerated by your build tools. Stale archives are only flagged when old and clearly unused.',
  },
}

const TOOL_ORDER: DeveloperTool[] = ['xcode', 'node', 'android', 'cocoapods', 'docker', 'general']

function ToolSection({ tool }: { tool: DeveloperTool }) {
  const meta = TOOL_META[tool]
  const cleanupItems = useAppStore((s) => s.cleanupItems)
  const items = useMemo(() => cleanupItems.filter((i) => i.tool === tool && !i.excluded), [cleanupItems, tool])
  const [open, setOpen] = useState(tool === 'xcode')
  const [whyOpen, setWhyOpen] = useState(false)

  const totalBytes = items.reduce((s, i) => s + i.sizeBytes, 0)
  const safeBytes = items.filter((i) => i.safety === 'green').reduce((s, i) => s + i.sizeBytes, 0)
  const reviewBytes = items.filter((i) => i.safety === 'orange').reduce((s, i) => s + i.sizeBytes, 0)

  if (tool === 'docker') {
    return (
      <Card className="opacity-70">
        <CardBody className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-surface-2 text-text-faint">
              <Container size={17} />
            </div>
            <div>
              <p className="text-[13px] font-medium text-text">{meta.label}</p>
              <p className="text-[12px] text-text-faint">Not connected in this prototype</p>
            </div>
          </div>
          <span className="rounded-full bg-surface-2 px-2.5 py-1 text-[11px] text-text-faint">Coming later</span>
        </CardBody>
      </Card>
    )
  }

  return (
    <Card className="overflow-hidden">
      <button onClick={() => setOpen((v) => !v)} className="flex w-full items-center justify-between gap-3 px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-accent-soft text-accent">
            <meta.icon size={17} />
          </div>
          <div className="text-left">
            <p className="text-[13px] font-medium text-text">{meta.label}</p>
            <p className="text-[12px] text-text-faint">{items.length} items detected</p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          <div className="hidden text-right sm:block">
            <p className="text-[13px] font-semibold text-text">{formatBytes(totalBytes)}</p>
            <p className="text-[11px] text-text-faint">
              <span className="text-safe">{formatBytes(safeBytes)} safe</span> ·{' '}
              <span className="text-review">{formatBytes(reviewBytes)} review</span>
            </p>
          </div>
          <ChevronDown size={16} className={open ? 'rotate-180 text-text-muted transition-transform' : 'text-text-muted transition-transform'} />
        </div>
      </button>

      <AnimatePresence>
        {open && (
          <motion.div initial={{ height: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }} className="overflow-hidden">
            <div className="border-t border-border px-5 py-3">
              <button
                onClick={() => setWhyOpen((v) => !v)}
                className="flex items-center gap-1.5 text-[12px] font-medium text-accent"
              >
                <HelpCircle size={13} />
                Why is this safe?
              </button>
              {whyOpen && <p className="mt-2 text-[12px] leading-relaxed text-text-muted">{meta.whySafe}</p>}
            </div>
            <div>
              {items.length === 0 ? (
                <p className="px-5 py-4 text-[13px] text-text-faint">No items detected for this tool.</p>
              ) : (
                items.map((item) => <CleanupItemRow key={item.id} item={item} />)
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </Card>
  )
}

export function Developer() {
  const cleanupItems = useAppStore((s) => s.cleanupItems)
  const selectIds = useAppStore((s) => s.selectIds)

  const developerItems = useMemo(
    () => cleanupItems.filter((i) => i.category === 'developer' && !i.excluded),
    [cleanupItems],
  )
  const totalBytes = developerItems.reduce((s, i) => s + i.sizeBytes, 0)

  function selectAllSafe() {
    selectIds(developerItems.filter((i) => i.safety === 'green').map((i) => i.id))
  }

  return (
    <div className="space-y-5 pb-16">
      <PageHeader
        title="Developer Cleanup"
        description="Xcode, Node, Android, CocoaPods, and general build artifacts — grouped by tool so you always know what created the data."
        actions={
          <Button variant="secondary" onClick={selectAllSafe}>
            Select all safe items
          </Button>
        }
      />

      <Card className="border-dashed">
        <CardBody className="flex items-center justify-between">
          <p className="text-[13px] text-text-muted">Total developer storage detected</p>
          <p className="text-lg font-semibold text-text">{formatBytes(totalBytes)}</p>
        </CardBody>
      </Card>

      <div className="space-y-3">
        {TOOL_ORDER.map((tool) => (
          <ToolSection key={tool} tool={tool} />
        ))}
      </div>
    </div>
  )
}
